// export const INCREMENT = 'INCREMENT';
export const actions = {
	LOGIN:"LOGIN",
	LTST:"LTSTT",
	SUCCESS_LOGIN:"ACTION_SUCCESS_LOGIN",
	ERROR_LOGIN:"ACTION—error",

	SUCCESS_LIST:"SUCCESS_LIST",
	ERROR_LIST:"ERROR_LIST",
	ONAUTHORIZATION:"ONAUTHORIZATION"
}